### ISSUE TITLE
Adding support for attaching images, files and videos

### ISSUE THREAD

**Issue by brandonopened** [opensalt/opensalt#393]
Currently, it is not possible to attach a file, image or video to OpenSALT fullstatement, notes or exemplar.

- [ ] OS Adding ICON for attachment for full statement, and notes   #262  PI7
    As a user, I want to be able to add an attachment to my comments when clicking an icon in the toolbar.
    
    Description: Icons for file & video, and an icon for pictures is desirable.
    
     
    
     
    
        
     
    
- [ ] OS Adding ICON for attachment for  Exemplar  #262  PI7
    As a user, I want to be able to add an attachment to description in Exemplar.
    
    Description: For Exemplar - a button to attach a file, picture or a video
    
     
    
     
    
     
    
     
    
        
     
    
- [ ] OS Enable File Storage  (attachment upload) PI7 #191
     Description:One possible solution is to use github file storage when users upload an image - This is related to both [#106](https://github.com/opensalt/opensalt/issues/106) and [#147](https://github.com/opensalt/opensalt/issues/147) (previous thought was for an AWS bucket but this seems better).
    
     making file storage configurable, how are we going to do that?
    
    concern - moving from internal and external - file transfer needs to be worked out.
    
    button on attachment for add and remove of attachment
    
     
    
     
    
      
    
    | As |  I WANT TO  | SO THAT |
    | --- | --- | --- |
    
- [ ] OS Adding attachment for full statement, notes - FILE or VIDEOS #262  PI7
     .Assumed that icons will be on the edit bar for Fullstatement and Notes, and available for Exemplar. There is a message for unrecognized file formats, if it is feasible to put the message in a tool tip, that would be good too. In that case the message would be same.
    
     
    
      
    
    | As an OS Editor |  I WANT TO edit Full Statement, Notes | SO THAT I can  attach a file or a video. |
    
- [ ] OS Adding attachment NOT NEEDED - PICTURES #262  PI7
    Markdown supports in-line pictures. 
    
    Description: As a user, I should be able to add an attachment to my comments when editing full statement, notes or exemplar.  The best outcome is that pictures can be attached or displayed on-line.
    
      
    
    | As an OS Editor |  I WANT TO edit Full Statement, Notes or Exemplar description | SO THAT I can place a PICTURE |
    
- [ ] OS Adding attachment for full statement, notes and Exemplar  VALIDATIONS #262  PI7
       Note: The maximum file size will be determined by the Spike task   [KMS-3541](https://agile.act.org/jira/browse/KMS-3541)
    
     
    
     
    
    | As an OS Editor |  I WANT TO add attachments to Full Statement, Notes or Exemplar description | SO THAT add attachments are validated for size and extension. |
    

Created from Aha! https://act.aha.io/features/ACKM-277

**Comment by brandonopened** [comment]
https://opensalt.mybalsamiq.com/projects/opensalt/Edit%20Item . to work with form view?
