### ISSUE TITLE
PI8 Adding support for attaching images, files, and videos

### ISSUE THREAD

**Issue by brandonopened** [opensalt/opensalt#541]
- [ ] OS Ability to add Inline Image via UI toolbar button #262 PI8
    Need to complete SPIKE KMS-4283: researching inline images before pointing
    
     
    
    As an OS editor  
     I want to be able to select a button to insert an inline image    
     So that I can add images to the Full Statement and Notes fields in 'Add' or 'Edit' modes
    
    **SCOPE**  
    The scope of this story is to allow users to click on a button in the toolbar in order to add embedded images to Full Statement or Notes fields.  Per Barb's note - Looks like code mirror doesn't allow alt text
    
    **OUT OF SCOPE**  
     Adding inline images to the Comments section is out of scope at this time.  Attachments story may take care of this (KMS-3929)
    
    Adding inline images via 'Import Children' is out of scope at this time
    
    **AUTOMATED ACCEPTANCE TEST CASES**  
     < need input from team>
    
    **DOMAIN**  
     Login to OS Staging environment:  [ [http://frameworks-staging.act.org/login](http://frameworks-staging.act.org/login)]
    
    - OS > Select Framework > Select Parent or Child Item > 'Edit' button > Full Statement AND Notes text box
    - OS > Select Framework > Select 'Add New Child Item' button > Full Statement AND Notes text box
    - OS > Select Framework > Select 'Export' button 
    - OS > Select Framework > Select 'Copy Framework' button  
      
    
    **DOCUMENTATION**
    
    [https://opensalt.mybalsamiq.com/projects/opensalt/CF%20Item%20Edit](https://opensalt.mybalsamiq.com/projects/opensalt/CF%20Item%20Edit)
    
- [ ] OS Attachment in Commenting:  Enable S3 bucket for external site #262 PI8
    Need to complete SPIKE KMS-4293 before this story
    
     
    
    As an OS user on the external site  
     I want the system updated  
     So that I can attach files to my comments
    
    **SCOPE**  
     The scope of this story is to enable the S3 bucket for the external site ( [http://frameworks-staging.act.org/](http://frameworks-staging.act.org/) and frameworks.act.org) in order to allow these users to attach files to comments.
    
    **OUT OF SCOPE**  
     KMS-3929 will update the system configuration to allow commenting with attachments
    
    **AUTOMATED ACCEPTANCE TEST CASES**  
    Repeat the test cases that the file is downloaded from S3 which by default also tests that it was uploaded
    
    **DOMAIN**  
     parameters.yml - maybe configuration elsewhere as well
    
    **DOCUMENTATION**  
     N/A
    
- [ ] OS Exemplar Adding attachment - FILE or VIDEOS #262  PI8
    As an OS Editor  
     I want to edit the 'Add Exemplar' popup  
     So that I can upload a file or video (file formats: doc, docx, txt, prn, pdf, csv, json, html, xml, mp3, mp4, mpeg, mpg, wav)
    
    **SCOPE**  
     The scope of this story is to allow the user to add either a URL (current functionality) or an uploaded attachment (file, picture, video) in Exemplar using AWS. 
    
    When the user clicks on the 'Add Exemplar' button, the pop up screen should be modified as shown in the wireframe (see documentation section below).  It would include 2 radio buttons and the option to add a URL or upload a file.  ~~Per backlog grooming meeting on 5/9/2018, drag and drop capability will also be implemented as part of this story.~~
    
    Only one exemplar can be added at a time.  Multiple Exemplars can be added but clicking on the 'Add Exemplar' button multiple times.
    
    If a file format is unrecognized, the following message should appear:
    
    - The file you are uploading must be in one of the following formats: doc, docx, txt, prn, pdf, csv, json, html, xml, mp3, mp4, mpeg, mpg, wav
    
    For file formats = .doc/.docx, when the user clicks on the Exemplar attachment, the file should download.  All other file types should open a new tab and display/run the file/video.  There is no file size limitation.
    
    For a successful upload, the attachment would be seen in the field.  For a failure, a pop-up message should occur.
    
    For a successful upload, the truncated file name should show on the detail screen after the attachment is added. 
    
    **OUT OF SCOPE**  
     The user will only be able to delete existing Exemplars.  No edit capability is needed  
     This story will be tested on ACT Internal server instances only.  It will not be deployed to external (Staging/Production) environments.
    
    **DOMAINS**  
    Select a Framework > Select a Parent/Child item > Click on a parent/child item > Click 'Add Exemplar' button > Popup is updated with radio buttons to add either a URL or uploaded attachment  
    **AUTOMATED ACCEPTANCE TEST CASES**  
    Confirm the ability to click on the 'Add Exemplar' button  
     Confirm the URL or uploaded attachment appears on the detail screen  
     Confirm the filename is being applied on S3
    
    **DOCUMENTATION**  
     [https://opensalt.mybalsamiq.com/projects/opensalt/Exemplar](https://opensalt.mybalsamiq.com/projects/opensalt/Exemplar)  
    
- [ ] OS Large Inline Images in the Editor
    As an OS Editor  
     I want the ability to limit large images that are exported into a PDF to the equivalent of the PDF size (in html size = 100%)  
     So that the image does not break the page
    
    **SCOPE**  
     The scope of this story is to ensure large images (any image that would be bigger than the editing box/wysiwyg editor) are allowed to be exported to a PDF and can be viewed without breaking the page.  Files types allowed in the export include: gif, jpg jpeg, png, tif, svg, pdf, json.    
     NOTE:  pdf & json attachments will display as non-clickable links.
    
    Test can use this image to test the functionality: [http://frameworks-staging.act.org/cftree/item/138997](http://frameworks-staging.act.org/cftree/item/138997)
    
    **Per SPIKE KMS-4256:**  
    
    Large Inline Images in the Editor1. In the Main framework to display the large inline image of 100% width following css needs to be updated,  
     .markdown-body img
    
    {  max-width: 100%;  box-sizing: content-box;  background-color: #fff; }
    
     
    
    2. Click on Edit framework then click on toggle side by side - To display large image following css needs to be added,  
       .editor-preview-active-side img
    
    {  max-width: 100%;  box-sizing: content-box;  background-color: #fff; }
    
    3. For Export PDF with large inline image following css needs to be added,   
       <img width=100; height=50; src =""; /> 
    
    **OUT OF SCOPE**  
     Resizing the image is not in the scope of this story
    
    **AUTOMATED ACCEPTANCE TEST CASES**  
     No automated test cases can be created for this story
    
    **DOMAIN**  
     Login to OS Staging environment:  [ [http://frameworks-staging.act.org/login](http://frameworks-staging.act.org/login)]
    
    - OS > Full Statement/Notes > add inline image that is larger than the editing box/wysiwyg editor
    - OS > Export to ensure PDFs render images properly
    
    **DOCUMENTATION**  
     N/A
    

Created from Aha! https://act.aha.io/features/ACKM-315

**Comment by roverwolf** [comment]
Relates to #262 #426 #476 #490 #494 #525 #541

**Comment by brandonopened** [comment]
closing. Image and file upload functionality works; will create ticket for documentation.
